# Base configs
baseurl: "https://cottonshop.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Kilian"
subtitle: "See the world through my eyes!"
author: "Kilian"
header:
 title: "Photography"
 subtitle: "by Kilian"
footer:
 name: "Hey there, my name is Kilian"
 bio: "I am a developer and a tech aficionado from Switzerland. Love making teeny tiny apps solving tiny problems in life and now learning photography."
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/kiliandesu"
